Debug and memcheck support overriding the target binary with $@. Added leaktest to perform leak checks against all tests/*_tests using valgrind.

diff --git a/debug b/debug
--- a/debug
+++ b/debug
@@ -1,2 +1,12 @@
 #!/usr/bin/env bash
+if [ $# -eq 0 ]; then
+    if [[ ! -x src/xy ]]; then
+        echo "no build available (src/xy missing)"
+        exit 1
+    fi
+    ARGS="src/xy"
+else
+    ARGS="$@"
+fi
+
 cgdb src/xy -- -d src -d lib
